export const ErrorCodes = {
  // Generic / Infrastructure
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Domain / Lifecycle Error Codes (from Phase 0.4 API Spec)
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVENTORY_CAPACITY_EXCEEDED: 'INVENTORY_CAPACITY_EXCEEDED',
  INVENTORY_HOLD_EXPIRED: 'INVENTORY_HOLD_EXPIRED',
  PAYMENT_GATEWAY_REJECTED: 'PAYMENT_GATEWAY_REJECTED',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',
  CANCELLATION_INELIGIBLE: 'CANCELLATION_INELIGIBLE',
  DOCUMENT_GENERATION_FAILED: 'DOCUMENT_GENERATION_FAILED',
  CONCURRENT_MUTATION_CONFLICT: 'CONCURRENT_MUTATION_CONFLICT',

  // Booking Engine Error Codes (Phase 5)
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_INVALID_STATE: 'BOOKING_INVALID_STATE',
  HOLD_NOT_FOUND: 'HOLD_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
